### ISSUE TITLE
Regarding "Pointer recievers, non-pointer receivers and the implementation of interfaces"

### ISSUE THREAD

**Issue by rtz12** [monsooncommerce/golang-tripping-hazards#2]
I just saw this on HackerNews and what you describe in this section as a limitation is actually possible!
Link: https://play.golang.org/p/5yXfOf6Y_3

**Comment by swsnider** [comment]
The error message printed by go is actually suggesting that you do the following;

```go
func WantsPointerToFooer(f Fooer) {
    fmt.Printf("I got a fooer, result of Foo() is %v\n", f.Foo())
}

func main(){
    var myInstance Fooer // declare as type Fooer
    myInstance = &ImplementsFooer{DataMember: 5}
    WantsPointerToFooer(myInstance)
}
```

instead of

```go
func WantsPointerToFooer(f *Fooer) {
    fmt.Printf("I got a fooer, result of Foo() is %v\n", f.Foo())
}

func main(){
    var myInstance Fooer // declare as type Fooer
    myInstance = ImplementsFooer{DataMember: 5}
    WantsPointerToFooer(&myInstance)
}
```

**Comment by danieltmiles** [comment]
oh, wow! Thank you so much! This is the clue I was missing! I'll edit this page to reflect it, thank you!

**Comment by danieltmiles** [comment]
@rtz12, @hopkinsth gave me a PR that addressed this same issue. I accepted that request and I'm going to close this for now unless you have something else to add. Again, thank you.
